vim.keymap.set('n', '<leader>e', ':Ex<CR>')
vim.keymap.set('n', '<leader>h', ':nohlsearch<CR>')
vim.keymap.set('n', '*', '*zz', { desc = 'Search and center screen' })
vim.keymap.set('n', '<leader>E', 'Y%', { remap = true, desc = 'Go to matching pair' })
vim.keymap.set('n', '<leader>bd', ':bdelete<cr>', { desc = 'delete buffer' })
vim.keymap.set('n', '<leader>bn', ':bnext<cr>', { desc = 'next buffer' })
vim.keymap.set('n', '<leader>bp', ':bprevious<cr>', { desc = 'previous buffer' })
