require("core.configs.alpha")
require("core.configs.telescope")
require("core.configs.treesitter")
require("core.configs.fugitive")
require("core.configs.lsp-config")
require("core.configs.lsp-rust")
require("core.configs.nvim-tree")
require("core.configs.theme")
require("core.configs.lualine")
require("core.configs.autocomplete")
require("core.configs.which-key")

--require("core.configs.bufferline")
