local builtin = require('telescope.builtin')
vim.keymap.set('n', '<c-p>', builtin.find_files, {})
-- vim.keymap.set('n', '<c-f>', builtin.live_grep, {})

vim.keymap.set('n', '<c-b>', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
-- vim.keymap.set('n', '<leader>ps', function()
vim.keymap.set('n', '<c-f>', function()
  builtin.grep_string({ search = vim.fn.input("Look for :: ") })
end)
