"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$shell\
$line_break\
$character\
"""

right_format = """
$nodejs\
$lua\
$rust\
$php\
$c\
"""

[character]
format = '[$symbol ](bold)'
success_symbol = "[󱞩](blue)"
error_symbol = "[](red)"
vimcmd_symbol = "[❮](green)"

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = "bright-blue"

[time]
time_format = "%R"
disabled = true
format = '$time'

[c]
format = '[ ]($style)'
style = "bright-cyan dimmed"

[lua]
format = '[ ]($style)'
style = "bright-cyan dimmed"

[rust]
format = '[ ]($style)'
style = "bright-cyan dimmed"

[php]
format = '[ ]($style)'
style = "bright-cyan dimmed"

[nodejs]
format = '[ ]($style)'
style = "bright-yellow dimmed"

[git_branch]
symbol = ''
format = ' [$symbol $branch]($style)'
style = "bright-black"

[git_state]
disabled = false
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted) ](218) ($ahead_behind$stashed) ]($style)"
style = "bright-blue bold"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

# [git_metrics]
# disabled = false
[cmd_duration]
# disabled = false
format = "[$duration]($style) "
style = "yellow dimmed"

[hostname]
disabled = false
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
