# Default colors
[colors.primary]
background = '#161617'
foreground = '#c9c7cd'

# Normal colors
[colors.normal]
black = '#27272a'
blue = '#9ca2cf'
cyan = '#85b5ba'
green = '#90b99f'
magenta = '#e29eca'
red = '#ea83a5'
white = '#c9c7cd'
yellow = '#e6b99d'

# Bright colors
[colors.bright]
black = '#353539'
blue = '#acb1d7'
cyan = '#97c0c4'
green = '#a7c8b3'
magenta = '#e8b0d4'
red = '#ed96b3'
white = '#c9c7cd'
yellow = '#eac5ae'
