# Alacritty Configuration
# Phosmon (Dark) theme

[colors]

# Default colors
[colors.primary]
background = "#1c1c1c"  # Softer black-gray background
foreground = "#d0d0d0"  # Brighter muted white for text

# Normal colors
[colors.normal]
black   = "#3e3e3e"   # Dark gray, lighter for contrast
red     = "#c57070"   # Warm, soft red
green   = "#6a9a60"   # Muted warm green
yellow  = "#c8c89a"   # Muted yellow, warm
blue    = "#4a94b3"   # Muted teal
magenta = "#a680a6"   # Softer purple
cyan    = "#707070"   # Softer gray
white   = "#e0e0e0"   # Slightly muted white

# Bright colors
[colors.bright]
black   = "#2c2c2c"   # Slightly lighter for reduced contrast
red     = "#c57070"   # Consistent red
green   = "#6a9a60"   # Brighter green
yellow  = "#c8c89a"   # Brighter yellow
blue    = "#4a94b3"   # Brighter teal
magenta = "#c0708f"   # Brighter pink
cyan    = "#707070"   # Consistent gray
white   = "#f2f2f2"   # Brighter white

