#!/bin/sh

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source $CONFIG_DIR/colors.sh # import color variables

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"
FONT="FiraCode Nerd Font"


# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

source $CONFIG_DIR/default.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

## -- Right items -- ##
source $ITEMS_DIR/cal.sh
source $ITEMS_DIR/vol.sh
# source $ITEMS_DIR/bat.sh
source $ITEMS_DIR/wifi.sh

## -- Center items -- ##
source $ITEMS_DIR/media.sh

## -- Left items -- ##
source $ITEMS_DIR/spaces.sh
source $ITEMS_DIR/fa.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."

