live_config_reload = true
import = [
  "~/.config/alacritty/themes/rose-pine-moon.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
decorations = "none"
opacity = 0.92
# dynamic_padding = true

[keyboard]
bindings = [
  { key = "Z", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
  { key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[font]
size = 20

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Regular"

# [font.offset]
# x = 0
# y = 0

[cursor.style]
shape = "Block"
blinking = "Always" 
