live_config_reload = true
import = [
  "~/.config/alacritty/themes/rose-pine.toml",
]

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["a", "-t", "Plugin"]

[window]
decorations = "none"
padding = { x = 8, y = 4 }
dynamic_padding = true
# blur = true
# opacity = 0.87

[keyboard]
bindings = [
  { key = "Z", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
  { key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[font]
size = 17

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font Mono"
style = "Italic"

[cursor.style]
shape = "Block"
blinking = "Always" 
