live_config_reload = true
import = [
  # "~/.config/alacritty/themes/rose-pine.toml"
  "~/.config/alacritty/themes/monokai_pro.toml"
]

[window] 
  decorations = "none"
  blur = false
  padding = { x = 0, y = 0 }
  dynamic_padding = true
  # opacity = 0.95

[keyboard]
  bindings = [
    { key = "Z", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
    { key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
  ]

[font] 
  # normal = { family = 'MesloLGS Nerd Font Mono', style = 'Regular' }
  normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
  bold = { family = 'JetBrainsMono Nerd Font Mono', style = 'Bold' }
  italic = { family = 'JetBrainsMono Nerd Font Mono', style = 'Italic' }
  size = 18

[cursor]
  style = { shape = "Block", blinking = "Always" }
