live_config_reload = true

[window] 
  decorations = "buttonless"
  blur = true
  padding = { x = 12, y = 12 }
  dynamic_padding = true
  opacity = 0.75

[keyboard]
  bindings = [
    { key = "F", mods = "Command|Shift", action = "ToggleFullscreen" },
  ]

[font] 
  normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
  size = 16.0

[cursor]
  style = { shape = "Block", blinking = "Always" }
