live_config_reload = true
import = [
  "~/.config/alacritty/themes/oldworld.toml",
]

[window]
padding = { x = 6, y = 6 }
decorations = "none"
blur = true
opacity = 0.93
dynamic_padding = true

[keyboard]
bindings = [
  { key = "Z", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
  { key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[font]
size = 16

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[cursor.style]
shape = "Block"
blinking = "Always" 
