import = [
  "~/.config/alacritty/keybindings.toml",
]

live_config_reload = true

[window] 
  decorations = "None"
  blur = true
  padding = { x = 12, y = 12 }
  dynamic_padding = true
  opacity = 0.9

[font] 
  normal = { family = 'JetBrainsMono Nerd Font', style = 'Regular' }
  # normal = { family = 'ZedMono Nerd Font Mono', style = 'Regular' }
  size = 16.0

[cursor]
  style = { shape = "Block", blinking = "Always" }
