live_config_reload = true

[window] 
  opacity = 0.85
  decorations = "None"
  dynamic_padding = true
  blur = true
  startup_mode = "Maximized"
  # startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"

[font] 
  # normal = { family = 'RobotoMono Nerd Font Mono', style = 'Regular' }
  normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
  size = 16.0

[cursor]
  style = { shape = "Block", blinking = "Always" }
