live_config_reload = true
import = [
  # "~/.config/alacritt/themes/rose-pine.toml"
  # "~/.config/alacritty/themes/monokai_pro.toml"
  "~/.config/alacritty/themes/kanagawa_dragon.toml"
]

[window] 
  decorations = "none"
  padding = { x = 4, y = 8 }
  dynamic_padding = true

[keyboard]
  bindings = [
    { key = "Z", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
    { key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
  ]

[font] 
  normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
  bold = { family = 'JetBrainsMono Nerd Font Mono', style = 'Bold' }
  italic = { family = 'JetBrainsMono Nerd Font Mono', style = 'Italic' }
  size = 16

[cursor]
  style = { shape = "Block", blinking = "Always" }
